# -*- coding: utf-8 -*-
"""AIML intern task 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1j4qpD4jd070kb57HEvxBvOMPDzJc5KcH
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

df = pd.read_csv("Titanic-Dataset.csv")

print(df.head())

print("\nSummary statistics:\n", df.describe())
print("\nInfo about dataset:\n", df.info())
print("\nMissing values:\n", df.isnull().sum())

numeric_features = ['Age', 'Fare', 'SibSp', 'Parch', 'Pclass']
df[numeric_features].hist(bins=15, figsize=(15,8), layout=(2,3))
plt.suptitle("Histograms of Numeric Features")
plt.show()

plt.figure(figsize=(15,8))
for i, col in enumerate(numeric_features):
    plt.subplot(2, 3, i+1)
    sns.boxplot(y=df[col])
    plt.title(f"Boxplot of {col}")
plt.tight_layout()
plt.show()

sns.pairplot(df[numeric_features + ['Survived']], hue='Survived', diag_kind='hist')
plt.suptitle("Pairplot of Numeric Features", y=1.02)
plt.show()

# Select only numeric columns
numeric_df = df.select_dtypes(include=['int64', 'float64'])

# Compute correlation
corr = numeric_df.corr()

# Plot correlation matrix
plt.figure(figsize=(10,7))
sns.heatmap(corr, annot=True, cmap='coolwarm', fmt=".2f")
plt.title("Correlation Matrix")
plt.show()

sns.countplot(x='Pclass', hue='Survived', data=df)
plt.title("Survival Count by Passenger Class")
plt.show()

sns.countplot(x='Sex', hue='Survived', data=df)
plt.title("Survival Count by Sex")
plt.show()

plt.figure(figsize=(10,6))
sns.kdeplot(df[df['Survived']==1]['Age'].dropna(), label='Survived', shade=True)
sns.kdeplot(df[df['Survived']==0]['Age'].dropna(), label='Not Survived', shade=True)
plt.title("Age Distribution by Survival")
plt.xlabel("Age")
plt.legend()
plt.show()

fig = px.scatter(df, x='Age', y='Fare', color='Survived',
                 hover_data=['Name', 'Pclass', 'Sex'],
                 title='Fare vs Age colored by Survival')
fig.show()

